apiVersion: v1
kind: Pod
metadata:
  name: hostpath-example
spec:
  containers:
  - name: my-container
    image: alpine
    volumeMounts:
    - mountPath: /data
      name: my-hostpath
  volumes:
  - name: my-hostpath
    hostPath:
      path: /mnt/data
      type: Directory