apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: redis
  name: daemonset
spec:
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - image: redis
        name: redis
