apiVersion: v1
kind: Pod
metadata:
  name: tolerated-pod
spec:
  containers:
  - image: nginx:latest
    name: tolerated-pod
  tolerations:
  - key: tur
    value: egitim
    operator: Equal
    effect: NoSchedule