apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: dns-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: dns-ns
spec:
  ports:
  - port: 80
  selector:
    app: nginx
  type: ClusterIP
