apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
spec:
  containers:
    - name: nginx-container
      image: nginx
      ports:
        - containerPort: 80
      volumeMounts:
        - name: log-volume
          mountPath: /usr/share/nginx/html/logs
    - name: log-writer-container
      image: busybox
      command: ['sh', '-c', 'while true; do date >> /usr/share/nginx/html/logs/uptime.log; sleep 60; done']
      volumeMounts:
        - name: log-volume
          mountPath: /usr/share/nginx/html/logs
  volumes:
    - name: log-volume
      emptyDir: {}

