apiVersion: batch/v1
kind: Job
metadata:
  name: pi-computation-job
spec:
  completions: 1
  backoffLimit: 4
  template:
    spec:
      containers:
      - name: pi
        image: perl
        command: ["perl", "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: OnFailure