apiVersion: v1
kind: Pod
metadata:
  labels:
    app: secret-env
  name: secret
spec:
  containers:
    - name: nginx-container
      image: nginx
      env:
        - name: APP_COLOR
          valueFrom:
            secretKeyRef:
              name: hamit-secret
              key: SECRET_COLOR
      ports:
        - containerPort: 80  
